### ISSUE TITLE
Doesn't install dependencies in AP + STA mode

### ISSUE THREAD

**Issue by ricard33** [MkLHX/AP_STA_RPI_SAME_WIFI_CHIP#14]
I've tried on fresh and small Raspberry PI OS install (custom build) with the example : 
```
curl https://raw.githubusercontent.com/MkLHX/AP_STA_RPI_SAME_WIFI_CHIP/master/ap_sta_config.sh | sudo bash -s -- --ap ap_ssid ap_passphrases --client client_ssid client_passphrase --country FR
```
and I have this error : 
```
Manage AP + STA modes on Raspberry Pi with the same wifi chip



started 2022/04/12-00:34:19


Populate /etc/udev/rules.d/70-persistent-net.rules


Populate /etc/dnsmasq.conf


Populate /etc/hostapd/hostapd.conf

bash: line 1: /etc/hostapd/hostapd.conf: No such file or directory
```

Dependencies are not installed due to test on line 187 
```
if test true != "${STA_ONLY}" && test true == "${AP_ONLY}"; then
```

**Comment by MkLHX** [comment]
Hi ricard33 what the distribution version of the Raspberry Pi OS ? buster or bullseye?
I don't know if this script works on bullseye.

About the line 187 this is just a test to manage only AP mode because deps are needed only when you wan't to use AP mode STA mode just write on the wpa_supplicant.conf file

Could you please chez hostapd is correctly installed.
The RPI is currently connected to internet when you try to run the script for the first time?

**Comment by ricard33** [comment]
Yes, this is on bullseye.
Ok for STA only, dependencies aren't needed. But they are installed only if we are in AP_ONLY, not if we are in STA + AP, due to this test.
So hostapd is not installed, and yes, the rpi is connected to Internet when running the script.
